### ISSUE TITLE
confusing license terms

### ISSUE THREAD

**Issue by graingert** [zaehlwerk/pep487#1]
> Note, PEP487 has been placed in the public domain.

> PEP487 is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

It doesn't make sense for PEP487 to be both placed in the public domain and GPLd

**Comment by grgi** [comment]
You are right, thanks for the hint! While the Python Enhancement Proposal 487 is placed in the public domain, but this package is GPLv3. I have created a new version 1.0.1 clearing this up.
